version: '3.7'
services:
        service_one:
                image: rajahamza104/service_one
                build: ./service_one
                ports:
                        - '5000:5000'
                depends_on:
                        - service_two
                        - service_three
                        - service_four
                environment:
                        - SECRET_KEY=${SECRET_KEY}
                deploy:
                        replicas: 8

        service_two:
                image: rajahamza104/service_two
                build: ./service_two
                ports:
                        - '5001:5001'
                deploy:
                        replicas: 8

        service_three:
                image: rajahamza104/service_three
                build: ./service_three
                ports:
                        - '5002:5002'
                deploy:
                        replicas: 8
        service_four:
                image: rajahamza104/service_four
                build: ./service_four
                ports:
                        - '5003:5003'
                deploy:
                        replicas: 8

        mysql:
                image: rajahamza104/dnd-sql
                build: ./db
                volumes:
                        - type: volume
                          source: dnd_sql
                          target: /var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: ${DB_PASS}
                        MYSQL_DATABASE: dnd-db
                ports:
                        - '3306:3306'


volumes:
        dnd_sql:
